# Recipe data for UNHINGED KITCHEN. Each recipe: name, chapter, weird (1-5), time (min), serves,
# hook (the TikTok opening line), why (the flavour logic), ingredients, steps, film (3 shots), text (on-screen text ideas), tip.
# free=True marks the ones that go in the free starter pack.

CHAPTERS = [
    ("sweet-salty", "Sweet × Salty", "Sugar makes salt taste saltier. Salt makes sugar taste sweeter. Everything in this chapter abuses that.", "#FF5A5F", "#FFE8E8"),
    ("spicy-sweet", "Spicy × Sweet", "Heat and sugar hit different receptors, so your brain reads them as one bigger flavour. This is why hot honey won.", "#FF7A1A", "#FFF0E0"),
    ("fat-acid", "Fat × Acid", "Fat coats your tongue; acid cuts through it. The combo makes rich things taste lighter and sour things taste rounder.", "#2EC4B6", "#E0F7F4"),
    ("umami", "Umami Bombs", "Miso, soy, parmesan, fish sauce, kimchi. Savory depth in places it has no business being. It belongs there.", "#7B61FF", "#ECE8FF"),
    ("texture", "Texture Chaos", "Crunchy on creamy. Chewy on crisp. Half the reason a food goes viral is the sound it makes.", "#FFC43D", "#FFF6DC"),
    ("breakfast", "Breakfast Rebellion", "Savory where it should be sweet, dessert where it should be sensible. Mornings were due a rethink.", "#06D6A0", "#DFF9F0"),
    ("drinks-dessert", "Drinks & Dessert Chaos", "The after-dinner chapter. Mostly five-ingredient things that look like they took effort.", "#EF476F", "#FDE2EA"),
]

RECIPES = [
    # ---------------- SWEET × SALTY ----------------
    dict(id=1, chapter="sweet-salty", name="Hot Honey Pickle Chips", weird=3, time=20, serves=2, free=True,
         hook="Fried pickles were already elite. Then I put hot honey on them.",
         why="Vinegar + salt + sugar + chili is the exact profile of a great wing sauce. The pickle just brings its own acid.",
         ingredients=["1 jar dill pickle chips, drained and patted very dry", "1/2 cup flour", "1 egg, beaten", "1 cup panko", "1 tsp garlic powder", "Neutral oil or an air fryer", "3 tbsp honey", "1 tsp chili flakes or 1 tbsp hot sauce", "Ranch, for dipping"],
         steps=["Dry the pickles hard with paper towel; wet pickles make soggy crumbs.", "Dredge: flour, then egg, then panko mixed with garlic powder.", "Air-fry 8 minutes at 200°C/400°F, flipping once, or shallow-fry 2 minutes a side until golden.", "Warm the honey with the chili for 30 seconds in the microwave.", "Drizzle the hot honey over the hot pickles. Serve with ranch."],
         film=["Shot 1: pickle slice dropping into panko, close-up.", "Shot 2: the honey drizzle in slow motion, hot pickles steaming.", "Shot 3: the crunch bite, reaction face."],
         text=["I didn't want to like this", "hot honey + pickles ??", "the crunch though"],
         tip="Sweet bread-and-butter pickles work too, but go lighter on the honey."),
    dict(id=2, chapter="sweet-salty", name="Peanut Butter Pickle Chip Sandwich", weird=5, time=5, serves=1, free=True,
         hook="This sandwich has been going viral since the 1940s and nobody believes it until they try it.",
         why="Peanut butter is fat and salt with a little sweetness. Pickles are acid and crunch. It's the same logic as a PB&J, with the jam's sugar swapped for vinegar.",
         ingredients=["2 slices soft white or brioche bread", "2 tbsp crunchy peanut butter", "6–8 dill pickle slices, patted dry", "A handful of salted potato chips", "Optional: a drizzle of honey or a few drops of hot sauce"],
         steps=["Spread peanut butter edge to edge on both slices. Both. This is non-negotiable.", "Lay the pickle slices on one side in a single layer.", "Crush a handful of potato chips on top of the pickles.", "Close, press gently, cut diagonally."],
         film=["Shot 1: peanut butter spread with a 'trust me' text.", "Shot 2: pickles laid out one by one, chips crushed on top.", "Shot 3: the cross-section cut, then the bite."],
         text=["everyone hates this until they try it", "PB + pickles + chips", "the crunch is illegal"],
         tip="Toast the bread lightly if you want it less soft."),
    dict(id=3, chapter="sweet-salty", name="Salted Pretzel Caramel Bark", weird=1, time=25, serves=8,
         hook="Three ingredients, one tray, and everyone at the party asks for the recipe.",
         why="Pretzel salt sits right on top of sweet caramel, so every bite alternates salty and sweet instead of blending.",
         ingredients=["250 g salted pretzels", "200 g soft caramels or 1 cup caramel sauce", "200 g dark chocolate", "Flaky sea salt"],
         steps=["Line a tray with baking paper and lay the pretzels flat in one layer.", "Melt the caramels with 1 tbsp water (microwave, 30-second bursts) and drizzle over the pretzels.", "Melt the chocolate the same way and pour over the top. Spread with a spatula.", "Sprinkle flaky salt. Fridge 15 minutes, then snap into shards."],
         film=["Shot 1: pretzels tiled on the tray, overhead.", "Shot 2: the chocolate pour.", "Shot 3: the snap, close to the mic."],
         text=["3 ingredients", "the snap sound", "gone in 10 minutes"]),
    dict(id=4, chapter="sweet-salty", name="Miso Chocolate Chip Cookies", weird=3, time=35, serves=16,
         hook="I put miso in chocolate chip cookies and now regular ones taste flat.",
         why="Miso is salt plus fermented umami. It does what sea salt does in a cookie, but deeper, like brown butter without browning anything.",
         ingredients=["115 g butter, soft", "100 g brown sugar", "50 g white sugar", "1 tbsp white miso", "1 egg", "1 tsp vanilla", "160 g flour", "1/2 tsp baking soda", "150 g chocolate chips or chopped dark chocolate", "Flaky salt"],
         steps=["Beat butter, both sugars and miso until creamy. Add egg and vanilla.", "Stir in flour and baking soda, then the chocolate.", "Scoop balls onto a lined tray, 5 cm apart. Chill 15 minutes if you can.", "Bake 11–12 minutes at 180°C/350°F until the edges set and the middles look underdone. Salt on top the second they come out."],
         film=["Shot 1: the miso spoon going into the dough with a 'wait what' text.", "Shot 2: cookies rising in the oven, timelapse.", "Shot 3: the pull-apart, melted chocolate stretch."],
         text=["miso in cookies", "umami cookie", "this ruined normal cookies for me"]),
    dict(id=5, chapter="sweet-salty", name="Olive Oil Ice Cream with Flaky Salt", weird=3, time=2, serves=1,
         hook="Rich people have been eating ice cream like this for years. It costs 30 seconds.",
         why="Good olive oil is fruity and peppery; vanilla is sweet and creamy. The oil adds richness and the salt makes the vanilla taste more like vanilla.",
         ingredients=["2 scoops good vanilla ice cream", "1 tbsp extra-virgin olive oil (the grassy, peppery kind)", "A pinch of flaky sea salt", "Optional: a few flakes of black pepper or chopped pistachio"],
         steps=["Scoop the ice cream into a cold bowl.", "Pour the olive oil over it in a thin stream.", "Flaky salt on top. Eat immediately."],
         film=["Shot 1: the oil pour onto the ice cream, slow.", "Shot 2: salt falling from height.", "Shot 3: the spoon drag through it."],
         text=["olive oil on ice cream", "the salt is the secret", "cost: 30 seconds"]),
    dict(id=6, chapter="sweet-salty", name="Watermelon, Feta & Mint with Tajín", weird=2, time=10, serves=4,
         hook="Watermelon and cheese sounds wrong until you remember salt makes fruit sweeter.",
         why="Feta is salty, watermelon is sweet and watery, mint is cold, Tajín adds lime and chili. It's a whole salad that tastes like one bite.",
         ingredients=["1/2 small watermelon, cubed", "100 g feta, crumbled", "A handful of mint leaves, torn", "1 lime", "1–2 tsp Tajín or chili-lime seasoning", "Olive oil"],
         steps=["Pile the watermelon on a plate; don't toss it, you'll bruise it.", "Scatter feta and mint on top.", "Squeeze lime over, drizzle a little olive oil, dust with Tajín."],
         film=["Shot 1: cubes being stacked, overhead.", "Shot 2: feta crumbled from above, then the Tajín dust.", "Shot 3: the bite with the mint."],
         text=["watermelon + feta", "the Tajín changes everything", "summer in one bite"]),
    dict(id=7, chapter="sweet-salty", name="Apple & Sharp Cheddar Grilled Cheese with Honey", weird=2, time=12, serves=1,
         hook="Apple pie with cheddar is a thing. This is the sandwich version.",
         why="Sharp cheddar is salty and tangy, apple is sweet and crisp, honey rounds it off. Grandparents in Vermont knew.",
         ingredients=["2 slices sourdough", "Butter", "80 g sharp cheddar, grated", "1/2 crisp apple, sliced thin", "1 tsp honey", "Pinch of black pepper"],
         steps=["Butter the outside of both slices.", "Layer cheddar, apple, pepper, more cheddar between them.", "Cook in a pan over medium heat, 3–4 minutes a side, pressing down, until deep gold and melted.", "Drizzle honey over the top before cutting."],
         film=["Shot 1: apple slices fanned onto the cheese.", "Shot 2: the flip, pan sizzle.", "Shot 3: the cheese pull with honey running down."],
         text=["apple in a grilled cheese", "sharp cheddar only", "the honey drizzle"]),
    dict(id=8, chapter="sweet-salty", name="Peanut Butter Bacon Smash Burger", weird=4, time=20, serves=2,
         hook="Peanut butter on a burger. I know. Try it once.",
         why="Peanut butter is fat, salt and a little sweetness, the same job a slice of American cheese does, plus roasted depth that loves bacon and beef.",
         ingredients=["300 g beef mince (80/20)", "4 rashers bacon", "2 tbsp smooth peanut butter", "2 burger buns", "2 slices American cheese", "Pickles, sliced", "Hot honey or sriracha (optional)", "Salt"],
         steps=["Fry the bacon until crisp; keep the pan.", "Split the mince into 4 balls. Press each flat onto the hot pan with a spatula, salt the top, cook 2 minutes, flip, add cheese, 1 minute more.", "Toast the buns in the bacon fat.", "Spread peanut butter on the top bun. Stack: patty, patty, bacon, pickles, a thread of hot honey."],
         film=["Shot 1: the smash, sizzle and crust.", "Shot 2: peanut butter spread on the bun with the 'wait' text.", "Shot 3: the stacked cross-section."],
         text=["PB on a burger", "trust the process", "I'm not sorry"]),

    # ---------------- SPICY × SWEET ----------------
    dict(id=9, chapter="spicy-sweet", name="Chili Crisp Vanilla Ice Cream", weird=4, time=2, serves=1, free=True,
         hook="The condiment that's on my eggs is now on my dessert and I'm not going back.",
         why="Chili crisp is oil, crunch, garlic, a little sugar and heat. Vanilla ice cream is cold fat and sugar. Fat loves fat; cold calms the heat; crunch finishes it.",
         ingredients=["2 scoops vanilla ice cream", "1–2 tsp chili crisp (the crunchy bits, not just the oil)", "Flaky salt", "Optional: crushed peanuts"],
         steps=["Scoop the ice cream.", "Spoon chili crisp over it, making sure you get the crispy bits.", "Salt. Peanuts if you have them. Eat before it melts."],
         film=["Shot 1: the jar of chili crisp next to the ice cream, 'hear me out' text.", "Shot 2: the spoonful landing on the scoop.", "Shot 3: the bite and the pause."],
         text=["hear me out", "chili crisp on ice cream", "sweet, salty, spicy, crunchy"]),
    dict(id=10, chapter="spicy-sweet", name="Hot Honey Pepperoni Pizza with Pickled Jalapeños", weird=2, time=15, serves=2,
         hook="Every pizza place that added hot honey saw sales go up. Here's the at-home version.",
         why="Pepperoni fat, jalapeño acid and chili, honey sugar. It's sweet, salty, sour and spicy on one slice.",
         ingredients=["1 store-bought pizza base or 2 naan", "1/2 cup pizza sauce", "150 g mozzarella", "Pepperoni", "Pickled jalapeños, drained", "2 tbsp honey + 1/2 tsp chili flakes"],
         steps=["Oven as hot as it goes with a tray inside.", "Sauce, cheese, pepperoni, jalapeños.", "Bake on the hot tray 8–10 minutes until the pepperoni cups and crisps.", "Warm the honey with the chili and drizzle over the whole pizza."],
         film=["Shot 1: pepperoni cupping in the oven, close.", "Shot 2: honey drizzle across the slices.", "Shot 3: the slice lift with the cheese pull."],
         text=["hot honey pizza", "the jalapeño is the move", "sweet heat"]),
    dict(id=11, chapter="spicy-sweet", name="Mango Chamoy Cups", weird=2, time=10, serves=2,
         hook="The fruit cup that outsells candy on every street corner in Mexico City.",
         why="Chamoy is sweet, sour, salty and a little hot, from pickled fruit. Mango is pure sugar. Tajín adds lime and crunchy salt.",
         ingredients=["2 ripe mangoes, cubed", "3 tbsp chamoy", "2 tsp Tajín", "1 lime", "Optional: cucumber sticks, jicama, watermelon"],
         steps=["Fill cups with mango (and anything else).", "Drizzle chamoy down the inside of the cup and over the fruit.", "Lime squeeze, heavy Tajín dust."],
         film=["Shot 1: chamoy running down the inside of a clear cup.", "Shot 2: mango dropped in, Tajín dusted.", "Shot 3: the first bite, lime wedge."],
         text=["mango + chamoy + Tajín", "street-corner fruit cup", "sour sweet spicy"]),
    dict(id=12, chapter="spicy-sweet", name="Gochujang Caramel Popcorn", weird=4, time=15, serves=4,
         hook="Caramel corn with Korean chili paste. Sticky, sweet, slow-burning.",
         why="Gochujang is sweet and savory already; caramel just amplifies the sweet side and the heat shows up late.",
         ingredients=["8 cups plain popped popcorn", "60 g butter", "100 g brown sugar", "1 tbsp gochujang", "1 tbsp golden syrup or honey", "1/4 tsp baking soda", "Flaky salt, sesame seeds"],
         steps=["Melt butter, sugar, gochujang and syrup in a pan; boil 2 minutes, stirring.", "Off the heat, stir in the baking soda (it foams).", "Pour over the popcorn and toss fast with two spoons.", "Spread on a tray, salt and sesame, let it set 10 minutes."],
         film=["Shot 1: the caramel foaming when the soda goes in.", "Shot 2: the pour over the popcorn.", "Shot 3: picking up a cluster, the crackle."],
         text=["gochujang caramel", "sweet then it hits", "movie night upgrade"]),
    dict(id=13, chapter="spicy-sweet", name="Sriracha Honey Butter Toast", weird=3, time=5, serves=1,
         hook="Honey butter toast is a Korean café classic. Add sriracha and it's dangerous.",
         why="Butter fat carries both the sugar and the capsaicin, so the heat is soft and the sweetness lingers.",
         ingredients=["1 thick slice brioche or milk bread", "1 tbsp soft butter", "1 tbsp honey", "1 tsp sriracha", "Pinch of flaky salt"],
         steps=["Mash the butter, honey and sriracha into a paste.", "Spread thick on the bread, edge to edge.", "Toast in a dry pan butter-side down over medium heat 2–3 minutes until caramelised, or under the grill.", "Flaky salt on top."],
         film=["Shot 1: the pink butter paste being spread.", "Shot 2: the pan sear, bubbling edges.", "Shot 3: tearing it apart."],
         text=["sriracha honey butter", "café toast at home", "don't skip the salt"]),
    dict(id=14, chapter="spicy-sweet", name="Spicy Pineapple Smash Tacos", weird=2, time=20, serves=2,
         hook="Pineapple on tacos is the pineapple-on-pizza debate but everyone agrees on this one.",
         why="Caramelised pineapple sugar against chili and salty pork is the al pastor principle. The lime makes it loud.",
         ingredients=["300 g pork or chicken mince", "1 tsp smoked paprika, 1 tsp cumin, 1/2 tsp chili powder, salt", "1 cup pineapple, small dice", "1 small red onion, diced", "6 small corn tortillas", "Coriander, lime, hot sauce"],
         steps=["Mix the mince with the spices and salt.", "Press a thin layer of mince onto each tortilla. Lay mince-side down in a hot, lightly oiled pan; cook 3 minutes until crisp, flip, 1 minute.", "Sear the pineapple in the same pan until the edges brown.", "Top each taco with pineapple, onion, coriander, lime, hot sauce."],
         film=["Shot 1: mince pressed onto the tortilla, pan sizzle.", "Shot 2: pineapple catching colour in the pan.", "Shot 3: the fold and bite."],
         text=["pineapple belongs here", "smash tacos", "sweet heat sour"]),
    dict(id=15, chapter="spicy-sweet", name="Chili-Lime Chocolate Strawberries", weird=3, time=20, serves=4,
         hook="Chocolate strawberries, but they bite back.",
         why="Dark chocolate is bitter-sweet, strawberry is sweet-sour, chili and lime zest make the whole thing taste brighter.",
         ingredients=["250 g strawberries, dry", "150 g dark chocolate", "Zest of 1 lime", "1/2 tsp chili flakes or Tajín", "Pinch of flaky salt"],
         steps=["Melt the chocolate in 30-second bursts, stirring.", "Dip each strawberry two-thirds in; let the excess drip.", "Place on baking paper; immediately sprinkle with lime zest, chili and salt.", "Fridge 10 minutes to set."],
         film=["Shot 1: the dip and drip.", "Shot 2: zest and chili falling on wet chocolate.", "Shot 3: the snap of the shell."],
         text=["chili chocolate strawberries", "lime zest is the secret", "valentine's upgrade"]),

    # ---------------- FAT × ACID ----------------
    dict(id=16, chapter="fat-acid", name="Balsamic Black Pepper Strawberries with Mascarpone", weird=3, time=10, serves=2, free=True,
         hook="Vinegar and black pepper on strawberries is a 400-year-old Italian trick and it still shocks people.",
         why="Balsamic adds acid and depth that makes strawberries taste riper; black pepper has a floral heat that reads as spice, not pain; mascarpone is the fat that pulls it together.",
         ingredients=["250 g strawberries, halved", "1 tbsp good balsamic vinegar", "1 tsp sugar", "Freshly cracked black pepper", "100 g mascarpone", "1 tsp honey"],
         steps=["Toss strawberries with balsamic and sugar. Leave 10 minutes.", "Mix mascarpone with honey.", "Spoon mascarpone onto plates, pile strawberries and their juice on top, crack black pepper over everything."],
         film=["Shot 1: balsamic pouring onto strawberries, 'wait' text.", "Shot 2: pepper mill over the top.", "Shot 3: the spoon through mascarpone and juice."],
         text=["vinegar on strawberries", "black pepper?!", "Italians knew"]),
    dict(id=17, chapter="fat-acid", name="Pickle-Brine Fried Chicken Tenders", weird=2, time=30, serves=2,
         hook="The secret ingredient at the most famous chicken chain is pickle juice. Here's how.",
         why="The brine's salt and acid season the meat and keep it juicy; the vinegar tang shows up against the fatty crust.",
         ingredients=["400 g chicken tenders or breast, in strips", "1 cup dill pickle brine", "1 cup flour", "1 tsp paprika, 1 tsp garlic powder, 1/2 tsp black pepper", "1 egg + 2 tbsp milk", "Oil for shallow frying", "Pickles and mayo for serving"],
         steps=["Soak the chicken in pickle brine for 30 minutes (up to 4 hours).", "Drain. Dip in egg-milk, then the seasoned flour, pressing it on.", "Shallow-fry 3–4 minutes a side until golden and 74°C/165°F inside.", "Serve with pickles and a mayo-hot-sauce dip."],
         film=["Shot 1: brine poured over the chicken with the 'secret' text.", "Shot 2: the flour press, then into the oil.", "Shot 3: the crunch tear."],
         text=["pickle juice chicken", "the chain's secret", "juiciest tenders ever"]),
    dict(id=18, chapter="fat-acid", name="Whipped Feta with Hot Honey & Lemon", weird=2, time=10, serves=4,
         hook="The dip that made people buy a food processor.",
         why="Feta is salty and sharp; cream cheese softens it; lemon lifts it; hot honey adds the sweet and heat. Four corners of flavour on one chip.",
         ingredients=["200 g feta", "100 g cream cheese", "2 tbsp olive oil", "Zest and juice of 1/2 lemon", "2 tbsp honey + chili flakes", "Pita chips or cucumber"],
         steps=["Blend feta, cream cheese, olive oil, lemon zest and juice until smooth and fluffy.", "Spread into a bowl with a swirl.", "Warm honey with chili; drizzle over. More olive oil, more zest."],
         film=["Shot 1: the blend turning fluffy.", "Shot 2: the spatula swirl in the bowl.", "Shot 3: hot honey drizzle, chip drag."],
         text=["whipped feta", "hot honey on top", "party dip in 10 min"]),
    dict(id=19, chapter="fat-acid", name="The Viral Smashed Cucumber Salad", weird=2, time=10, serves=2, free=True,
         hook="The cucumber salad that got millions of people to buy a mandoline.",
         why="Smashing bruises the cucumber so it drinks the dressing: rice vinegar for acid, sesame oil for fat, garlic and chili for aroma. Cold, crunchy, sour, savory.",
         ingredients=["2 cucumbers", "1 tsp salt", "1 tbsp rice vinegar", "1 tbsp soy sauce", "1 tsp sesame oil", "1 tsp sugar", "1 clove garlic, grated", "1 tsp chili crisp", "Sesame seeds"],
         steps=["Smash the cucumbers with the flat of a knife, then chop into chunks.", "Salt them, 5 minutes, pour off the water.", "Mix the dressing; toss through the cucumber.", "Chili crisp and sesame on top. Eat cold."],
         film=["Shot 1: the smash, overhead.", "Shot 2: dressing poured over, glossy.", "Shot 3: the crunch, mic close."],
         text=["smashed cucumber salad", "10 minutes", "the crunch is the content"]),
    dict(id=20, chapter="fat-acid", name="Grated Egg Avocado Toast", weird=2, time=10, serves=1,
         hook="Grating a boiled egg turned avocado toast into something people photograph again.",
         why="Grated egg is fluffy fat and protein; avocado is creamy fat; lemon and chili keep it from being heavy. The grated texture is the whole trick.",
         ingredients=["1 slice sourdough, toasted", "1/2 avocado", "1 hard-boiled egg, cold", "Lemon juice", "Chili flakes, flaky salt", "Olive oil"],
         steps=["Mash the avocado with lemon and salt onto the toast.", "Grate the egg over it on the fine side of a box grater, like snow.", "Olive oil, chili, salt."],
         film=["Shot 1: avocado spread, overhead.", "Shot 2: the egg grating, slow, falling.", "Shot 3: oil drizzle and the bite."],
         text=["grated egg", "egg snow", "avocado toast but make it fluffy"]),
    dict(id=21, chapter="fat-acid", name="Sour Cream & Brown Sugar Strawberries", weird=3, time=3, serves=1,
         hook="My grandmother's weird dessert is the best thing you can do with three ingredients.",
         why="Sour cream is fat with lactic acid; brown sugar is molasses-sweet. Together they taste like a cheesecake that took no effort.",
         ingredients=["A bowl of strawberries, whole", "A small bowl of full-fat sour cream", "A small bowl of brown sugar"],
         steps=["Dip a strawberry in sour cream.", "Then in brown sugar.", "Eat. Repeat."],
         film=["Shot 1: the two bowls with the 'trust me' text.", "Shot 2: dip, dip, the sugar crust.", "Shot 3: the bite."],
         text=["sour cream + brown sugar", "3 ingredients", "grandma was right"]),
    dict(id=22, chapter="fat-acid", name="Dill Pickle Pasta Salad", weird=3, time=20, serves=4,
         hook="Pickle people, this one's yours.",
         why="Creamy mayo is pure fat; pickles and brine are acid and salt; dill is the fresh note. It's a potato salad that ate a jar of pickles.",
         ingredients=["250 g small pasta (shells or ditalini)", "1 cup dill pickles, diced", "3 tbsp pickle brine", "1/2 cup mayo", "1/4 cup sour cream", "100 g sharp cheddar, cubed small", "1/4 cup fresh dill, chopped", "Black pepper"],
         steps=["Cook the pasta, drain, rinse cold.", "Whisk mayo, sour cream, brine and pepper.", "Toss pasta with the dressing, pickles, cheddar and dill. Chill 30 minutes if you can."],
         film=["Shot 1: pickles diced, brine poured into the mayo.", "Shot 2: the big stir, creamy.", "Shot 3: forkful with dill on top."],
         text=["dill pickle pasta salad", "pickle people rise", "BBQ side that wins"]),

    # ---------------- UMAMI BOMBS ----------------
    dict(id=23, chapter="umami", name="Ramen Carbonara", weird=3, time=10, serves=1, free=True,
         hook="Instant ramen and a carbonara had a baby. It costs about a dollar.",
         why="Egg yolk and cheese emulsify with the starchy ramen water into a sauce; the ramen seasoning is already salty umami.",
         ingredients=["1 pack instant ramen", "1 egg yolk + 1 whole egg", "30 g parmesan, grated", "2 rashers bacon or pancetta, chopped", "Black pepper, lots"],
         steps=["Fry the bacon until crisp. Off the heat.", "Cook the noodles in just enough water to cover; save 3 tbsp of the water and drain.", "Whisk eggs, parmesan, half the seasoning packet and pepper.", "Add the hot noodles to the bacon pan (heat off), pour in the egg mix and the saved water, toss fast until glossy. More parmesan and pepper."],
         film=["Shot 1: the egg yolk dropping into cheese.", "Shot 2: the toss, sauce turning glossy.", "Shot 3: the noodle lift, pepper crack."],
         text=["ramen carbonara", "$1 dinner", "glossy"]),
    dict(id=24, chapter="umami", name="Soy Sauce Vanilla Ice Cream", weird=5, time=2, serves=1,
         hook="Soy sauce on ice cream is the salted caramel of Japan. Three drops. That's it.",
         why="Soy sauce is salt plus fermented sweetness and umami; on vanilla it reads as caramel with a savory edge. Too much and it's soup, so three drops.",
         ingredients=["2 scoops vanilla ice cream", "3–5 drops good soy sauce (not more)", "Optional: toasted sesame seeds or crushed rice crackers"],
         steps=["Scoop the ice cream.", "Drop the soy sauce over it from a spoon, three to five drops, scattered.", "Sesame on top. Taste one bite before adding more."],
         film=["Shot 1: the soy bottle over the ice cream, 'no' text.", "Shot 2: exactly three drops landing.", "Shot 3: the reaction."],
         text=["soy sauce on ice cream", "3 drops", "tastes like caramel"]),
    dict(id=25, chapter="umami", name="Kimchi Grilled Cheese", weird=2, time=12, serves=1,
         hook="The grilled cheese that makes people say 'why is this so good' with their mouth full.",
         why="Kimchi brings acid, chili, garlic and fermented funk; melted cheese brings fat and salt. It's a tangy, crunchy, gooey argument.",
         ingredients=["2 slices sourdough", "Butter or mayo for the outside", "80 g mozzarella or cheddar, grated", "1/2 cup kimchi, chopped and squeezed dry", "1 tsp gochujang (optional)"],
         steps=["Squeeze the kimchi dry so the bread doesn't go soggy. Fry it in a dry pan 1 minute to caramelise.", "Butter (or mayo) the outsides of the bread. Spread gochujang inside if using.", "Cheese, kimchi, cheese. Close.", "Medium heat, 3–4 minutes a side, pressing, until crisp and melted."],
         film=["Shot 1: kimchi sizzling in the pan.", "Shot 2: the sandwich press, crust forming.", "Shot 3: the cheese pull with red kimchi."],
         text=["kimchi grilled cheese", "sour + melty", "best grilled cheese upgrade"]),
    dict(id=26, chapter="umami", name="Miso Caramel Sauce", weird=3, time=15, serves=8,
         hook="Salted caramel is over. Miso caramel is the sequel.",
         why="Miso replaces the salt in salted caramel and adds fermented depth, so the caramel tastes richer and less sweet.",
         ingredients=["200 g sugar", "60 ml water", "120 ml heavy cream, warm", "40 g butter", "1 tbsp white miso", "1 tsp vanilla"],
         steps=["Sugar and water in a pan; don't stir, swirl. Cook until deep amber, 8–10 minutes.", "Off the heat, pour in the cream carefully (it will bubble). Stir in butter.", "Whisk in the miso and vanilla until smooth.", "Cool. Pour on ice cream, apples, pancakes, a spoon."],
         film=["Shot 1: sugar turning amber, swirl.", "Shot 2: the cream going in, the bubble-up.", "Shot 3: the miso whisk, glossy ribbon."],
         text=["miso caramel", "salted caramel's sequel", "put it on everything"]),
    dict(id=27, chapter="umami", name="Baked Feta Pasta with Chili Crisp", weird=1, time=35, serves=4,
         hook="The pasta that sold out feta in two countries, with the upgrade it needed.",
         why="Roasted tomatoes bring sweet acid, feta brings salty creaminess, chili crisp adds crunch, garlic and heat the original was missing.",
         ingredients=["400 g cherry tomatoes", "200 g block feta", "4 cloves garlic", "1/4 cup olive oil", "300 g pasta", "2 tbsp chili crisp", "Basil"],
         steps=["Tomatoes, garlic and oil in a baking dish, feta in the middle. Bake 30 minutes at 200°C/400°F.", "Cook the pasta; save a cup of water.", "Mash the feta and tomatoes into a sauce, add pasta and splashes of water until creamy.", "Chili crisp and basil on top."],
         film=["Shot 1: the feta block in the tomatoes, before.", "Shot 2: the mash, after the oven.", "Shot 3: pasta tossed, chili crisp spoon."],
         text=["baked feta pasta 2.0", "chili crisp fixed it", "4 servings, 7 ingredients"]),
    dict(id=28, chapter="umami", name="Sushi Bake", weird=2, time=30, serves=4,
         hook="Sushi, but you eat it with a spoon out of a casserole dish.",
         why="Vinegared rice, creamy mayo, salty crab or salmon, savory furikake. All the sushi flavours, no rolling.",
         ingredients=["2 cups cooked sushi rice + 2 tbsp rice vinegar + 1 tsp sugar", "250 g imitation crab or cooked salmon, flaked", "1/2 cup Kewpie mayo", "2 tbsp sriracha", "2 tbsp cream cheese, soft", "Furikake", "Nori sheets, cucumber, avocado, soy sauce"],
         steps=["Season the rice with vinegar and sugar; press into a baking dish. Furikake on top.", "Mix crab, mayo, sriracha and cream cheese; spread over the rice.", "Bake 15 minutes at 200°C/400°F; grill 2 minutes to brown.", "Scoop onto nori squares with cucumber and avocado."],
         film=["Shot 1: the rice pressed into the dish, furikake rain.", "Shot 2: the creamy layer spread, then broiled bubbling.", "Shot 3: scoop onto nori, fold, bite."],
         text=["sushi bake", "no rolling", "feeds 4 for cheap"]),
    dict(id=29, chapter="umami", name="Fish Sauce Caramel Wings", weird=4, time=40, serves=3,
         hook="Fish sauce in caramel sounds like a dare. It's the best wing sauce in Vietnam.",
         why="Caramel is sweet and slightly bitter; fish sauce is salt and deep umami; lime and chili cut through. Sticky, funky, addictive.",
         ingredients=["1 kg chicken wings", "1 tbsp cornflour, salt", "60 g sugar", "2 tbsp water", "2 tbsp fish sauce", "1 tbsp lime juice", "1 clove garlic, grated", "1 red chili, sliced", "Spring onion, crushed peanuts"],
         steps=["Toss wings in cornflour and salt; bake 35 minutes at 220°C/425°F until crisp, or air-fry.", "Cook sugar and water to amber, then carefully add fish sauce, lime, garlic and chili. Simmer 1 minute.", "Toss the hot wings in the sauce. Top with spring onion and peanuts."],
         film=["Shot 1: wings out of the oven, crackling.", "Shot 2: fish sauce into the caramel, the hiss.", "Shot 3: the toss, sticky coat."],
         text=["fish sauce caramel", "sounds wrong, tastes right", "sticky wings"]),

    # ---------------- TEXTURE CHAOS ----------------
    dict(id=30, chapter="texture", name="Crispy Rice Salad", weird=2, time=30, serves=4, free=True,
         hook="Leftover rice, baked until it shatters, in a salad. The sound is the recipe.",
         why="Crunchy rice against soft herbs and a sour-sweet dressing. Texture contrast is the whole point.",
         ingredients=["2 cups cooked rice, cold (day-old is best)", "2 tbsp oil", "1 cucumber, diced", "1 cup edamame", "Handful mint and coriander", "Dressing: 2 tbsp lime juice, 1 tbsp fish sauce or soy sauce, 1 tbsp honey, 1 tsp chili crisp", "Peanuts"],
         steps=["Toss the rice with oil and spread thin on a tray. Bake 25 minutes at 220°C/425°F, stirring once, until golden and crunchy.", "Mix the dressing.", "Toss cucumber, edamame and herbs with the dressing; add the crispy rice right before eating.", "Peanuts on top."],
         film=["Shot 1: the rice tray, golden, crackling.", "Shot 2: dressing shaken in a jar.", "Shot 3: the toss and the crunch, mic close."],
         text=["crispy rice salad", "leftover rice glow-up", "the sound"]),
    dict(id=31, chapter="texture", name="Pasta Chips", weird=3, time=25, serves=4,
         hook="Pasta that crunches. Dip it like a chip.",
         why="Cooked pasta dried out in the air fryer goes glassy and crisp; parmesan and salt make it taste like a savory cracker.",
         ingredients=["250 g short pasta (farfalle or rigatoni)", "2 tbsp olive oil", "30 g parmesan, grated", "1 tsp Italian seasoning, 1/2 tsp garlic powder, salt", "Marinara for dipping"],
         steps=["Cook the pasta 1 minute less than the packet. Drain, toss with oil, parmesan and seasonings.", "Air-fry 10–12 minutes at 200°C/400°F, shaking twice, until crisp. (Oven: 20 minutes, one layer.)", "Cool 5 minutes; they crisp more. Dip in marinara."],
         film=["Shot 1: pasta tossed in cheese, overhead.", "Shot 2: the air fryer basket shake.", "Shot 3: the dip and crunch."],
         text=["pasta chips", "crunchy pasta", "marinara is the dip"]),
    dict(id=32, chapter="texture", name="Cottage Cheese Cookie Dough", weird=4, time=5, serves=2,
         hook="High-protein cookie dough that you eat with a spoon. No eggs, no baking.",
         why="Blended cottage cheese is creamy and salty; oats give the chew; chocolate chips do the rest. Tastes like dough, has 20 g protein.",
         ingredients=["1 cup cottage cheese", "2 tbsp peanut butter", "2 tbsp maple syrup or honey", "1 tsp vanilla", "1/2 cup oat flour (blend oats)", "Pinch of salt", "1/4 cup mini chocolate chips"],
         steps=["Blend cottage cheese, peanut butter, syrup and vanilla until completely smooth.", "Stir in oat flour and salt until thick like dough.", "Fold in the chips. Chill 20 minutes for the best texture."],
         film=["Shot 1: cottage cheese going into the blender, 'hear me out'.", "Shot 2: the smooth result, chips folded in.", "Shot 3: the spoonful."],
         text=["cottage cheese cookie dough", "20 g protein", "no it doesn't taste like cottage cheese"]),
    dict(id=33, chapter="texture", name="Smash Tacos", weird=1, time=20, serves=2,
         hook="Smash burgers, but tacos. Crispy edges, melted cheese, two minutes each.",
         why="Pressing the mince onto the tortilla gives a lace-edge crust; cheese melts into the meat; the tortilla fries in the fat.",
         ingredients=["300 g beef mince", "1 tsp cumin, 1 tsp smoked paprika, salt", "6 small flour tortillas", "6 slices American cheese", "Onion, coriander, lime, salsa or hot sauce"],
         steps=["Mix mince with the spices.", "Press a thin layer onto each tortilla. Lay mince-down in a hot, lightly oiled pan; 3 minutes until the edges crisp.", "Flip, add cheese, 1 minute.", "Fold with onion, coriander, lime, salsa."],
         film=["Shot 1: the smash in the pan, crackling edges.", "Shot 2: cheese melting as it flips.", "Shot 3: the fold and the bite."],
         text=["smash tacos", "crispier than a burger", "2 min each"]),
    dict(id=34, chapter="texture", name="Dubai Chocolate Bar (Pistachio Kataifi)", weird=2, time=40, serves=6,
         hook="The chocolate bar with a waiting list. You can make it in a muffin tin.",
         why="Toasted kataifi (shredded filo) is pure crunch; pistachio cream is rich and sweet; the chocolate shell snaps. Crunch inside creamy inside snap.",
         ingredients=["100 g kataifi pastry, chopped", "2 tbsp butter", "150 g pistachio cream or pistachio butter + 2 tbsp honey", "1 tbsp tahini", "250 g milk or dark chocolate", "Pinch of salt"],
         steps=["Toast the kataifi in the butter over medium heat, stirring, 8 minutes until golden and crisp.", "Mix with pistachio cream and tahini.", "Melt the chocolate. Brush a layer into a silicone bar or muffin mould; freeze 5 minutes.", "Fill with the pistachio mix, cover with chocolate, freeze 15 minutes. Unmould, salt."],
         film=["Shot 1: kataifi toasting, golden strands.", "Shot 2: the green filling going into the shell.", "Shot 3: the snap and the cross-section."],
         text=["Dubai chocolate at home", "the crunch", "cheaper than the viral one"]),
    dict(id=35, chapter="texture", name="Snickers Dates", weird=2, time=20, serves=6, free=True,
         hook="A date, peanut butter, chocolate and salt. It tastes like a Snickers and takes 20 minutes.",
         why="Dates are caramel; peanut butter is the nougat; chocolate shell; flaky salt makes the sweetness pop. Chewy, creamy, snappy.",
         ingredients=["12 medjool dates", "1/4 cup peanut butter", "12 roasted peanuts", "150 g dark chocolate", "Flaky salt"],
         steps=["Slit the dates, pull the stones out.", "Fill each with a teaspoon of peanut butter and press a peanut on top.", "Dip in melted chocolate; lay on baking paper; salt.", "Freeze 10 minutes. Keep in the fridge."],
         film=["Shot 1: the stone popping out, peanut butter in.", "Shot 2: the chocolate dip and drip.", "Shot 3: the bite, the caramel stretch."],
         text=["snickers dates", "healthier snickers", "20 minutes"]),
    dict(id=36, chapter="texture", name="Grinder Salad Sandwich", weird=1, time=15, serves=2,
         hook="The sandwich where the salad is the sauce. Crunchy, creamy, sour, in every bite.",
         why="Shredded lettuce dressed with mayo and vinegar is creamy and crunchy at once; cold cuts and provolone bring the salt; toasted bread the crack.",
         ingredients=["1 baguette or 2 hoagie rolls", "150 g sliced deli meats", "4 slices provolone", "2 cups iceberg, shredded", "3 tbsp mayo", "1 tbsp red wine vinegar", "1/4 red onion, sliced thin", "Pepperoncini, oregano, salt, pepper"],
         steps=["Toast the bread with the cheese and meat on it until the cheese melts.", "Toss lettuce, onion and pepperoncini with mayo, vinegar, oregano, salt and pepper.", "Pile the salad on, close, press, cut."],
         film=["Shot 1: the lettuce toss, creamy.", "Shot 2: salad piled high on the melted cheese.", "Shot 3: the press and the cross-section."],
         text=["grinder sandwich", "the salad is the sauce", "crunch in every bite"]),

    # ---------------- BREAKFAST REBELLION ----------------
    dict(id=37, chapter="breakfast", name="Everything Bagel Cottage Cheese Bowl", weird=2, time=5, serves=1, free=True,
         hook="25 grams of protein, zero cooking, and it tastes like a bagel with cream cheese.",
         why="Cottage cheese is the cream cheese; everything seasoning brings the garlic, onion, sesame and salt; cucumber adds crunch.",
         ingredients=["1 cup cottage cheese", "1 tbsp everything bagel seasoning", "1/2 cucumber, sliced", "6 cherry tomatoes, halved", "Olive oil", "Optional: smoked salmon, avocado"],
         steps=["Cottage cheese in a bowl.", "Cucumber, tomatoes, salmon or avocado around it.", "Olive oil, then a heavy shake of everything seasoning."],
         film=["Shot 1: the cottage cheese scoop, overhead.", "Shot 2: toppings arranged, seasoning rain.", "Shot 3: the first spoon."],
         text=["everything bagel bowl", "25 g protein", "no cooking"]),
    dict(id=38, chapter="breakfast", name="Savory Oats with Jammy Egg & Chili Crisp", weird=4, time=12, serves=1,
         hook="Oatmeal is a blank canvas and we've only ever painted it with sugar.",
         why="Oats cooked with stock taste like congee; a jammy egg adds richness; chili crisp adds crunch, heat and garlic.",
         ingredients=["1/2 cup rolled oats", "1 cup chicken or veg stock", "1 egg", "1 tbsp chili crisp", "1 spring onion, sliced", "1 tsp soy sauce", "Sesame seeds"],
         steps=["Simmer the oats in stock 5 minutes until creamy.", "Boil the egg 6.5 minutes, cool in cold water, peel, halve.", "Oats in a bowl, soy on top, egg halves, chili crisp, spring onion, sesame."],
         film=["Shot 1: stock pouring over oats with 'savory oats?' text.", "Shot 2: the jammy egg cut.", "Shot 3: chili crisp spoon, the swirl."],
         text=["savory oats", "oatmeal congee", "breakfast glow-up"]),
    dict(id=39, chapter="breakfast", name="Kimchi Fried Rice Omelette", weird=3, time=15, serves=1,
         hook="Kimchi fried rice wrapped in an omelette. Breakfast and dinner in one pan.",
         why="Fermented chili rice is sour and spicy; the egg blanket is soft and mild; a swipe of ketchup-sriracha on top makes it a Korean diner classic.",
         ingredients=["1 cup cold cooked rice", "1/2 cup kimchi, chopped", "1 tsp kimchi juice", "1 tsp sesame oil", "2 eggs, beaten with a pinch of salt", "Ketchup + sriracha", "Spring onion, sesame"],
         steps=["Fry the kimchi in sesame oil 2 minutes; add rice and kimchi juice, fry 3 minutes, pressing to crisp.", "In another pan, pour the eggs into a thin layer over low heat; when just set, slide the rice onto one half and fold.", "Ketchup-sriracha stripe, spring onion, sesame."],
         film=["Shot 1: rice crisping in the kimchi oil.", "Shot 2: the omelette fold over the rice.", "Shot 3: the sauce stripe, the cut."],
         text=["kimchi fried rice omelette", "one pan", "diner classic"]),
    dict(id=40, chapter="breakfast", name="Peanut Butter, Banana & Bacon Wrap", weird=4, time=10, serves=1,
         hook="Elvis ate this as a sandwich. The wrap version is faster and messier.",
         why="Peanut butter fat, banana sugar, bacon salt and smoke. Three big flavours that each make the others louder.",
         ingredients=["1 large flour tortilla", "2 tbsp peanut butter", "1 banana", "2 rashers bacon, cooked crisp", "Honey, cinnamon"],
         steps=["Crisp the bacon.", "Spread peanut butter on the tortilla, lay the whole banana and the bacon on it, honey and cinnamon.", "Roll tight. Sear in the bacon pan 1 minute a side until the tortilla is golden. Slice in half."],
         film=["Shot 1: peanut butter spread, banana laid down whole.", "Shot 2: the bacon on top, the roll.", "Shot 3: the sear and the cross-section."],
         text=["the Elvis wrap", "PB + banana + bacon", "no notes"]),
    dict(id=41, chapter="breakfast", name="Chocolate Protein Pudding", weird=2, time=5, serves=1,
         hook="Dessert for breakfast with 30 grams of protein and nothing weird in it.",
         why="Greek yogurt is thick and tangy; cocoa and protein powder make it taste like mousse; a little salt and maple hide the tang.",
         ingredients=["1 cup Greek yogurt", "1 scoop chocolate protein powder", "1 tbsp cocoa", "1 tbsp maple syrup", "Pinch of salt", "Splash of milk", "Toppings: berries, peanut butter, cacao nibs"],
         steps=["Whisk everything except toppings until smooth, adding milk until it's pudding-thick.", "Chill 10 minutes if you can.", "Toppings. Eat."],
         film=["Shot 1: the whisk going from lumpy to glossy.", "Shot 2: the spoon drag.", "Shot 3: toppings dropped from above."],
         text=["protein pudding", "30 g protein", "tastes like mousse"]),
    dict(id=42, chapter="breakfast", name="Savory Yogurt Bowl", weird=3, time=5, serves=1,
         hook="Yogurt with olive oil and cucumber instead of berries. The Mediterranean has been doing this forever.",
         why="Thick yogurt is sour and creamy; olive oil adds fruit and fat; za'atar and cucumber make it a salad you eat with a spoon.",
         ingredients=["1 cup thick Greek yogurt", "1/2 cucumber, diced", "2 tbsp olive oil", "1 tsp za'atar", "Flaky salt", "Pita or crackers"],
         steps=["Yogurt in a bowl, swirl it.", "Cucumber on top, olive oil over everything, za'atar and salt.", "Scoop with pita."],
         film=["Shot 1: the yogurt swirl.", "Shot 2: oil pooling, za'atar dust.", "Shot 3: pita scoop."],
         text=["savory yogurt", "breakfast in Beirut", "swap the berries"]),
    dict(id=43, chapter="breakfast", name="Hash Brown Waffles", weird=2, time=15, serves=2,
         hook="Hash browns in a waffle iron. Crispier than any pan.",
         why="The waffle iron presses the potato thin on two sides at once; maximum surface area, maximum crunch.",
         ingredients=["2 cups frozen hash browns, thawed, squeezed dry", "1 egg", "2 tbsp grated parmesan", "Salt, pepper", "Oil spray", "Fried egg and hot sauce to serve"],
         steps=["Mix hash browns, egg, parmesan, salt and pepper.", "Spray the waffle iron, pack the potato in, close and cook 8–10 minutes until deep gold and it releases easily.", "Fried egg on top, hot sauce."],
         film=["Shot 1: potato packed into the iron.", "Shot 2: the lift, steam and crust.", "Shot 3: egg yolk breaking over it."],
         text=["hash brown waffle", "crispiest hash browns", "waffle iron hack"]),

    # ---------------- DRINKS & DESSERT CHAOS ----------------
    dict(id=44, chapter="drinks-dessert", name="Sleepy Girl Mocktail", weird=2, time=3, serves=1, free=True,
         hook="Tart cherry juice, magnesium and sparkling water. The bedtime drink TikTok made famous.",
         why="Tart cherry is sour and a little bitter; magnesium powder is fizzy and faintly sweet; soda makes it feel like a cocktail. Treat it as a nice drink, not medicine.",
         ingredients=["1/2 cup tart cherry juice", "1 tsp magnesium powder (the drink kind)", "Sparkling water", "Ice, a lime wedge"],
         steps=["Ice in a glass.", "Cherry juice, stir in the magnesium powder.", "Top with sparkling water. Lime."],
         film=["Shot 1: the cherry pour over ice.", "Shot 2: the fizz when the soda hits.", "Shot 3: the sip in dim light."],
         text=["sleepy girl mocktail", "bedtime drink", "tastes like a cocktail"],
         tip="Check the magnesium label for serving size; the drink works just as well without it."),
    dict(id=45, chapter="drinks-dessert", name="Espresso Tonic with Orange", weird=3, time=3, serves=1,
         hook="Coffee and tonic water. Sounds wrong, tastes like a summer in Scandinavia.",
         why="Tonic's bitterness and bubbles match espresso's bitterness; orange adds sweet acid. Bitter plus bitter plus citrus somehow reads as refreshing.",
         ingredients=["1 double espresso, cooled slightly", "150 ml tonic water, cold", "Ice", "A strip of orange peel"],
         steps=["Fill a tall glass with ice. Pour in the tonic.", "Pour the espresso slowly over the top so it layers.", "Twist the orange peel over the glass and drop it in."],
         film=["Shot 1: tonic over ice, bubbles.", "Shot 2: the espresso layering down, slow.", "Shot 3: the orange twist spray."],
         text=["espresso tonic", "coffee + tonic water", "summer coffee"]),
    dict(id=46, chapter="drinks-dessert", name="Olive Oil Dark Chocolate Mousse", weird=3, time=15, serves=4,
         hook="Chocolate mousse with olive oil instead of cream. Four ingredients, restaurant texture.",
         why="Olive oil's fruitiness lifts dark chocolate's bitterness; the whipped egg whites make it light; salt sharpens everything.",
         ingredients=["150 g dark chocolate (70%)", "60 ml extra-virgin olive oil", "3 eggs, separated", "3 tbsp sugar", "Pinch of salt", "Flaky salt to finish"],
         steps=["Melt the chocolate; stir in the olive oil and the egg yolks.", "Whisk whites with the sugar and salt to soft peaks.", "Fold whites into the chocolate in three goes, gently.", "Spoon into glasses, chill 2 hours. Flaky salt and a thread of oil on top."],
         film=["Shot 1: oil swirling into melted chocolate.", "Shot 2: the fold, streaks disappearing.", "Shot 3: the spoon into the set mousse."],
         text=["olive oil chocolate mousse", "4 ingredients", "restaurant texture"],
         tip="Room-temperature whites whip faster and fuller. Use a spotless bowl: any grease or yolk stops them peaking."),
    dict(id=47, chapter="drinks-dessert", name="Tiramisu Oreo Cups", weird=2, time=20, serves=4,
         hook="Tiramisu for people who don't own ladyfingers.",
         why="Oreos soaked in coffee go cake-soft; mascarpone and cream are the rich layer; cocoa is the bitter top. Same architecture, five minutes of effort.",
         ingredients=["16 Oreos", "1/2 cup strong coffee, cooled", "250 g mascarpone", "150 ml heavy cream", "3 tbsp sugar", "1 tsp vanilla", "Cocoa powder"],
         steps=["Whip cream, sugar and vanilla to soft peaks; fold in the mascarpone.", "Dip each Oreo in coffee for 2 seconds; layer in cups with the cream.", "Repeat, finish with cream and a thick dust of cocoa. Chill 1 hour."],
         film=["Shot 1: the Oreo dip, 2 seconds.", "Shot 2: layers building in a clear cup.", "Shot 3: cocoa dust, spoon through."],
         text=["oreo tiramisu", "no ladyfingers", "4 cups, 20 minutes"]),
    dict(id=48, chapter="drinks-dessert", name="Salted Pretzel Milkshake", weird=2, time=5, serves=2,
         hook="Fries in a Frosty, but you can make it in a blender.",
         why="Salty pretzel crumbs in sweet vanilla ice cream, with a caramel swirl. Salty-sweet with crunch in a straw.",
         ingredients=["3 scoops vanilla ice cream", "1/2 cup milk", "1 cup salted pretzels + more for the rim", "2 tbsp caramel sauce", "Whipped cream"],
         steps=["Blend ice cream, milk and most of the pretzels until thick with crumbs.", "Swirl caramel inside the glass; rim it with crushed pretzel.", "Pour, whipped cream, more pretzel, caramel drizzle."],
         film=["Shot 1: pretzels dropping into the blender.", "Shot 2: caramel swirled inside the glass.", "Shot 3: the pour, the topping stack."],
         text=["pretzel milkshake", "salty sweet", "fries in a frosty energy"]),
    dict(id=49, chapter="drinks-dessert", name="Salted Watermelon Juice with Lime & Chili", weird=2, time=5, serves=2,
         hook="A pinch of salt makes watermelon juice taste twice as sweet. Chili makes it a drink you crave.",
         why="Salt suppresses bitterness and amplifies sweetness; lime adds acid; chili adds a tingle. Agua fresca with an edge.",
         ingredients=["4 cups watermelon, cubed", "Juice of 1 lime", "1/4 tsp salt", "Pinch of chili powder or Tajín for the rim", "Ice, mint"],
         steps=["Blend watermelon, lime and salt. Strain if you want it smooth.", "Rim the glasses with lime and Tajín.", "Pour over ice, mint on top."],
         film=["Shot 1: salt pinch into pink juice with 'why' text.", "Shot 2: the Tajín rim.", "Shot 3: the pour over ice."],
         text=["salted watermelon juice", "salt makes it sweeter", "Tajín rim"]),
    dict(id=50, chapter="drinks-dessert", name="Miso Caramel Latte", weird=4, time=8, serves=1,
         hook="The salted caramel latte with a secret: the salt is miso.",
         why="Miso's salt and umami make caramel taste deeper and less sugary; in milk and espresso it reads like a grown-up caramel latte.",
         ingredients=["1 double espresso", "200 ml milk", "2 tbsp miso caramel (recipe 26) or 1 tbsp caramel sauce + 1/2 tsp white miso", "Ice (optional)"],
         steps=["Stir the miso caramel into the hot espresso until dissolved.", "Steam or froth the milk (or shake with ice for iced).", "Pour the milk over the espresso. A thread of caramel on the foam."],
         film=["Shot 1: caramel stirred into dark espresso.", "Shot 2: the milk pour, the colour change.", "Shot 3: the caramel drizzle on the foam."],
         text=["miso caramel latte", "the salt is miso", "café drink at home"]),
]

assert len(RECIPES) == 50 and len({r["id"] for r in RECIPES}) == 50
FREE_IDS = [r["id"] for r in RECIPES if r.get("free")]
assert len(FREE_IDS) == 10, FREE_IDS

PANTRY = [
    ("Chili crisp", "Crunch, heat, garlic and oil in one jar. Goes on eggs, ice cream, pasta, salad."),
    ("Hot honey", "Or make it: honey + chili flakes, 30 seconds in the microwave."),
    ("White miso", "The salt that tastes like more. Cookies, caramel, butter, soup."),
    ("Tajín / chili-lime salt", "Fruit, rims, popcorn, anything that needs lime and crunchy salt."),
    ("Flaky sea salt", "Finishing salt. It's the difference between 'nice' and 'why is this so good'."),
    ("Dill pickles + their brine", "Acid, salt and crunch. The brine is a free marinade."),
    ("Good olive oil", "Fruity and peppery. Ice cream, mousse, yogurt, toast."),
    ("Rice vinegar", "Gentler than white vinegar. Cucumbers, rice, dressings."),
    ("Kewpie mayo", "Richer, eggier. Sushi bake, sandwiches, dips."),
    ("Gochujang", "Sweet, savory chili paste. Caramel, butter, marinades."),
    ("Kimchi", "Sour, spicy, crunchy. Grilled cheese, fried rice, eggs."),
    ("Fish sauce", "Smells aggressive, tastes like depth. Caramel, dressings, wings."),
    ("Everything bagel seasoning", "Garlic, onion, sesame, salt. Cottage cheese, eggs, avocado."),
    ("Dark chocolate (70%)", "Mousse, bark, dates, strawberries."),
    ("Peanut butter", "Fat, salt, sweetness. Sandwiches, burgers, dates, dough."),
    ("Cottage cheese", "The 2020s' most reinvented ingredient. Dough, bowls, dips."),
    ("Instant ramen", "A starch, a seasoning packet and a dare."),
    ("Medjool dates", "Nature's caramel. Snickers dates, smoothies, boards."),
    ("Limes", "Acid for everything. Buy a bag."),
    ("Parmesan", "Umami you can grate. Pasta chips, carbonara, waffles."),
]

PRINCIPLES = [
    ("Salt makes sweet sweeter", "A pinch of salt suppresses bitterness and makes your tongue read sugar as stronger. Flaky salt on caramel, chocolate, watermelon, ice cream."),
    ("Acid cuts fat", "Rich foods taste heavy until something sour arrives. Pickles with peanut butter, lime on tacos, balsamic on mascarpone."),
    ("Fat carries heat", "Capsaicin dissolves in fat, so butter, oil and cream make chili taste rounder and last longer. Hot honey butter, chili crisp on ice cream."),
    ("Sweet softens spice", "Sugar and heat hit different receptors; together they read as one bigger, friendlier flavour. Gochujang caramel, hot honey pizza."),
    ("Umami is depth, not a flavour you taste", "Miso, soy, parmesan, fish sauce, kimchi make everything around them taste more like itself. Three drops of soy on vanilla."),
    ("Texture is half the taste", "Crunch on creamy is the most shareable sound in food. Crispy rice, grated egg, pretzel in a shake, kataifi in chocolate."),
]

HOOKS = [
    "I didn't want to like this.", "Hear me out.", "Everyone hates this until they try it.", "This has been viral since the 1940s.",
    "Rich people have eaten it like this for years.", "The secret ingredient at the famous chain is ___.", "I put ___ in ___ and now regular ones taste flat.",
    "Three ingredients. One tray. Everyone asks for the recipe.", "The condiment on my eggs is now on my dessert.", "Sounds like a dare. Tastes like the best thing you'll eat this week.",
    "My grandmother's weird dessert is a 3-ingredient masterpiece.", "This cost me about a dollar.", "The sound is the recipe.", "Pickle people, this one's yours.",
    "Salt makes fruit sweeter. Watch.", "Trust the process.", "I'm not sorry.", "Italians have done this for 400 years.",
    "Stop scrolling, you have everything for this.", "The upgrade the viral recipe needed.", "This is why hot honey won.", "You're going to say no. Then you're going to make it twice.",
    "Breakfast and dinner in one pan.", "25 g of protein, zero cooking.", "Dessert for breakfast, no regrets.", "Restaurant texture, four ingredients.",
    "Tiramisu for people who don't own ladyfingers.", "The chocolate bar with a waiting list, in a muffin tin.", "Cheaper than the viral one.", "The drink TikTok made famous, done right.",
    "Rate my weird combo 1-10.", "Would you try this?", "Chaos in the kitchen, part 7.", "The combo that broke my friend group.",
    "POV: you grew up with this and didn't know it was weird.", "Things I eat that make my boyfriend leave the room.", "Tell me it's not just me.", "The internet was right about this one.",
    "I tested the viral ___ so you don't have to.", "Day 12 of weird food combos that actually work.",
]

# Allergen tagging: keyword (lowercase, substring) -> allergen label. "Check labels" items vary by brand.
ALLERGEN_RULES = [
    (["peanut"], "peanuts"),
    (["pistachio", "almond", "walnut", "cashew", "pecan", "hazelnut", "crushed nuts"], "tree nuts"),
    (["butter", "milk", "cheese", "cheddar", "feta", "mozzarella", "parmesan", "provolone", "mascarpone", "cream", "yogurt", "ice cream", "ranch", "caramel", "brioche", "whipped", "ghee", "paneer", "chocolate"], "dairy"),
    (["egg", "mayo", "kewpie", "brioche", "ranch"], "eggs"),
    (["flour", "bread", "sourdough", "bun", "flour tortilla", "pasta", "ramen", "panko", "pretzel", "oreo", "kataifi", "pita", "baguette", "hoagie", "naan", "pizza", "cracker", "soy sauce", "toast", "filo", "ladyfinger", "oats", "oat flour", "imitation crab", "gochujang"], "wheat/gluten"),
    (["soy", "miso", "tofu", "edamame", "gochujang", "chili crisp", "oreo", "chocolate", "kimchi"], "soy"),
    (["fish sauce", "imitation crab", "salmon", "furikake", "kimchi", "tuna", "anchov"], "fish/shellfish"),
    (["sesame", "tahini", "everything bagel", "furikake", "za'atar", "zaatar"], "sesame"),
]
# Ingredients whose allergens vary by brand: (keyword, what to call it on the page).
CHECK_LABEL = [
    ("chili crisp", "chili crisp"), ("chocolate", "chocolate"), ("kimchi", "kimchi"), ("gochujang", "gochujang"),
    ("oreo", "Oreos"), ("caramel", "caramel"), ("ranch", "ranch"), ("imitation crab", "imitation crab"),
    ("oats", "oats"), ("oat flour", "oats"), ("miso", "miso"), ("furikake", "furikake"),
    ("everything bagel", "everything seasoning"), ("protein powder", "protein powder"), ("magnesium", "magnesium powder"),
    ("ice cream", "ice cream"), ("ramen", "ramen seasoning"), ("deli meat", "deli meats"), ("bun", "buns"),
    ("naan", "naan"), ("pizza base", "pizza base"), ("stock", "stock"), ("pepperoni", "pepperoni"),
    ("pistachio cream", "pistachio cream"), ("corn tortilla", "corn tortillas"), ("fish sauce", "fish sauce"),
]

DAIRY_WORDS = ["butter", "milk", "cheese", "cheddar", "feta", "mozzarella", "parmesan", "provolone", "mascarpone", "cream",
               "yogurt", "ice cream", "ranch", "caramel", "brioche", "whipped", "ghee", "chocolate"]
WHEAT_WORDS = ["flour,", "flour\"", " flour", "bread", "bun", "pasta", "ramen", "panko", "pretzel", "oreo", "kataifi", "pita",
               "baguette", "hoagie", "naan", "pizza", "cracker", "soy sauce", "toast", "oats", "gochujang", "imitation crab"]


def allergens(recipe):
    """Returns (allergens found, ingredients to check on the label)."""
    text = " | ".join(recipe["ingredients"]).lower().replace("cornflour", "cornstarch").replace("corn flour", "cornstarch")
    found = []
    for keys, label in ALLERGEN_RULES:
        if any(k in text for k in keys) and label not in found:
            found.append(label)
    # Peanut butter is dairy-free; a recipe whose only "butter" hit is "peanut butter" isn't dairy.
    if "dairy" in found and not any(k in text.replace("peanut butter", "").replace("pistachio butter", "") for k in DAIRY_WORDS):
        found.remove("dairy")
    # Corn tortillas are gluten-free; only flour tortillas count.
    if "wheat/gluten" in found and "tortilla" in text and "flour tortilla" not in text and not any(k in text for k in WHEAT_WORDS):
        found.remove("wheat/gluten")
    check = []
    for k, name in CHECK_LABEL:
        if k in text and name not in check:
            check.append(name)
    return found, check


# Flavour stats, 0-5 each: sweet, salty, sour, spicy, umami, crunch.
PROFILE = {
    1: "344315", 2: "243014", 3: "540004", 4: "530032", 5: "420101", 6: "433212", 7: "332033", 8: "242152",
    9: "420323", 10: "342442", 11: "524201", 12: "530325", 13: "421313", 14: "333433", 15: "413302",
    16: "403210", 17: "043135", 18: "343221", 19: "134234", 20: "022123", 21: "403001", 22: "044022",
    23: "040151", 24: "430031", 25: "044344", 26: "530030", 27: "242342", 28: "232252", 29: "442354",
    30: "234235", 31: "041045", 32: "421011", 33: "042244", 34: "510015", 35: "530012", 36: "043234",
    37: "141023", 38: "030352", 39: "133342", 40: "430022", 41: "312001", 42: "033013", 43: "030235",
    44: "304000", 45: "203000", 46: "320000", 47: "510001", 48: "530002", 49: "423200", 50: "420030",
}
assert sorted(PROFILE) == list(range(1, 51)) and all(len(v) == 6 and v.isdigit() for v in PROFILE.values())

# Safety notes for recipes with a real hazard (hot oil, molten sugar, raw or runny egg, raw meat, caffeine, supplements).
SAFETY = {
    1: "Hot oil spits. Pat the pickles bone-dry, lower them in away from you and never leave the pan. Microwaved honey gets very hot.",
    2: "Peanut allergy alert. Use a clean knife, board and jar if you're also making food for someone allergic.",
    3: "Melted caramel stays hot for minutes and sticks to skin. Let it cool a little before touching the tray.",
    4: "Raw dough has raw egg and raw flour, so bake it before eating. Oven gloves for the hot tray.",
    8: "Cook beef mince until no pink remains (71°C/160°F). Bacon fat spits: keep your face and phone back from the pan.",
    9: "Many chili crisps contain soy, and some contain peanuts or sesame. Read the jar before serving guests.",
    10: "The oven and tray will be at full heat. Use oven gloves and keep the door clear of kids and pets.",
    12: "Boiling sugar is far hotter than boiling water and foams up when the soda goes in. Big pan, long spoon, kids clear.",
    13: "Under the grill, sugar goes from caramelised to burnt and smoking in seconds. Don't walk away.",
    14: "Cook the mince right through: pork to 71°C/160°F, chicken to 74°C/165°F. Wash hands after handling it raw.",
    15: "Wash your hands after handling chili and keep them away from your eyes.",
    17: "Chicken must hit 74°C/165°F in the thickest piece. Bin the brine after soaking; never reuse it. Hot oil spits.",
    19: "Smash with the flat of the knife, blade facing away from you, fingers clear of the edge.",
    22: "Keep this creamy salad cold. Don't leave it out for more than 2 hours (1 hour on a hot day).",
    23: "The eggs are only gently cooked by the noodles. Use pasteurised eggs for anyone pregnant, very young, older or immunocompromised.",
    26: "Caramel runs at about 170°C/340°F and erupts when the cream goes in. Pour slowly at arm's length, long sleeves on.",
    27: "The dish and its oil come out at 200°C/400°F. Oven gloves, and open the oven door away from your face.",
    28: "Serve it hot and refrigerate leftovers within 2 hours. Fish, eggs, soy, wheat and sesame are all in this one.",
    29: "Wings must reach 74°C/165°F. Fish sauce hitting hot caramel hisses and spits, so add it at arm's length.",
    30: "Cool leftover rice fast, refrigerate it within an hour and use it within a day. Contains peanuts.",
    31: "Don't overfill the air fryer, and never preheat it with an empty paper liner inside.",
    32: "Rolled oats are heat-treated, which is why this is fine raw. Don't swap in raw wheat flour.",
    33: "Cook beef mince until no pink remains (71°C/160°F). Hot fat spits, so keep your phone back from the pan.",
    34: "Melted butter and chocolate burn. Tree nuts, sesame, wheat and dairy are all in this one.",
    35: "Check every date for stones. Peanut allergy alert.",
    38: "The jammy yolk stays runny. Use pasteurised eggs for anyone pregnant, very young, older or immunocompromised.",
    39: "Cook the eggs until set for anyone vulnerable. Cool and refrigerate leftover rice within an hour.",
    40: "Bacon fat spits, and a seared banana holds heat like lava. Let it cool a minute before biting.",
    41: "Protein powders vary: check the label for dairy, soy and serving size. Not for young kids.",
    43: "Waffle irons get very hot and steam hard when opened. Lift the lid away from you.",
    44: "Magnesium isn't for everyone: ask a doctor or pharmacist if you're pregnant, on medication or have kidney issues. Not for kids.",
    45: "A double espresso has roughly 120-150 mg of caffeine. Not for kids; count it toward your limit if pregnant.",
    46: "The eggs stay raw, yolks and whites. Use pasteurised eggs, and skip it for anyone pregnant, very young, older or immunocompromised.",
    47: "Contains coffee. Use decaf if kids are eating it.",
    50: "Contains caffeine. Making the caramel fresh? Read the safety note on recipe 26 first.",
}
